# Real estate report - Selection and Frequency

In [21]:
import pandas as pd
df_realestate = pd.read_csv('data/aluguel.csv', sep=';')
df_realestate.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN

## 1. how many apartments are in the database

In [7]:
df_apartment = df_realestate.query('Tipo=="Apartamento"')
print("There are {} apartments in the database".format(len(df_apartment)))

There are 19532 apartments in the database

## 2. how many Casa, Casa de Condominio, Casa de Vila are in the database

In [11]:

df_casa = df_realestate.query('Tipo in ("Casa", "Casa de Condomínio", "Casa de Vila")')
print("There are {} houses in the database".format(df_casa.shape[0]))

There are 2212 houses in the database

In [16]:
# another approach for same selection
casa_selection = (df_realestate['Tipo'] == "Casa") | (df_realestate['Tipo'] == "Casa de Condomínio")  | (df_realestate['Tipo'] == "Casa de Vila")
df_casa = df_realestate[casa_selection]
df_casa

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
7,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,NaN,NaN
8,Casa de Condomínio,Ramos,2,2,0,65,1000.0,NaN,NaN
18,Casa de Condomínio,Taquara,3,1,1,115,2000.0,NaN,NaN
22,Casa de Condomínio,Barra da Tijuca,4,3,2,466,7500.0,2695.0,NaN
31,Casa,Campo Grande,4,1,2,400,12000.0,NaN,NaN
59,Casa de Condomínio,Barra da Tijuca,5,10,5,1600,25000.0,1600.0,NaN
74,Casa,Méier,2,0,0,51,1500.0,50.0,NaN
82,Casa,São Conrado,4,2,4,730,28000.0,2000.0,12000.0
85,Casa de Condomínio,Freguesia (Jacarepaguá),5,3,1,140,2500.0,1200.0,NaN
117,Casa de Vila,Piedade,2,1,0,70,1300.0,NaN,NaN
138,Casa,Maracanã,8,3,5,259,7000.0,NaN,NaN
142,Casa,Benfica,1,0,0,33,1200.0,NaN,NaN
216,Casa,Jardim Carioca,3,2,1,135,3000.0,NaN,NaN
236,Casa,Lins de Vasconcelos,2,0,0,40,950.0,NaN,50.0
248,Casa de Condomínio,Barra da Tijuca,4,2,4,595,30000.0,2500.0,2510.0
253,Casa de Condomínio,Recreio dos Bandeirantes,4,4,4,267,6500.0,700.0,3308.0
269,Casa,Tijuca,4,1,1,191,4000.0,300.0,NaN
272,Casa de Condomínio,São Conrado,3,2,1,250,5500.0,750.0,500.0
306,Casa de Condomínio,Barra da Tijuca,4,4,4,1000,30000.0,2695.0,23715.0
312,Casa de Vila,Jardim Sulacap,2,1,2,115,1600.0,1.0,60.0
324,Casa de Vila,Oswaldo Cruz,1,0,1,40,800.0,NaN,NaN
327,Casa de Condomínio,Freguesia (Jacarepaguá),2,1,0,163,1800.0,92.0,46.0
357,Casa,Grajaú,5,4,2,450,7000.0,NaN,500.0
367,Casa de Condomínio,Vargem Grande,2,2,1,90,1700.0,618.0,338.0
372,Casa,Tanque,2,1,0,59,1200.0,170.0,NaN
378,Casa,Campo Grande,3,0,0,200,2100.0,NaN,NaN
390,Casa de Condomínio,Barra da Tijuca,5,6,5,640,13800.0,980.0,1800.0
400,Casa,Bonsucesso,2,0,0,51,1000.0,NaN,NaN
401,Casa de Condomínio,Barra da Tijuca,5,3,5,1000,20000.0,1800.0,1800.0
...,...,...,...,...,...,...,...,...,...
32613,Casa,Andaraí,3,1,0,75,2950.0,NaN,NaN
32620,Casa de Vila,Quintino Bocaiúva,2,0,0,58,1000.0,NaN,NaN
32644,Casa,Lagoa,3,3,1,250,8600.0,1900.0,580.0
32652,Casa,Engenho Novo,1,0,0,40,450.0,NaN,NaN
32656,Casa de Condomínio,Leblon,6,3,6,1206,55000.0,3200.0,5016.0
32681,Casa de Condomínio,Copacabana,2,1,1,80,3000.0,50.0,NaN
32686,Casa de Vila,Todos os Santos,3,1,1,92,1500.0,80.0,11.0
32698,Casa de Condomínio,Recreio dos Bandeirantes,4,4,4,350,9000.0,550.0,3000.0
32732,Casa,Maracanã,4,2,1,240,6500.0,NaN,700.0
32739,Casa,Campo Grande,2,1,2,86,1500.0,NaN,NaN
32769,Casa de Condomínio,Barra da Tijuca,5,3,5,900,20000.0,1300.0,1600.0
32772,Casa de Condomínio,Barra da Tijuca,3,3,3,400,7500.0,1900.0,NaN
32777,Casa de Condomínio,Itanhangá,3,2,3,200,3600.0,480.0,NaN
32778,Casa,Vila da Penha,2,1,0,80,1500.0,NaN,NaN
32792,Casa de Condomínio,Recreio dos Bandeirantes,4,4,3,500,9000.0,1000.0,900.0
32796,Casa de Condomínio,Barra da Tijuca,4,4,2,600,30000.0,1050.0,NaN
32804,Casa de Vila,Riachuelo,3,0,0,73,850.0,NaN,NaN
32807,Casa de Condomínio,Barra da Tijuca,4,3,4,300,10000.0,1055.0,5500.0
32853,Casa de Condomínio,Barra da Tijuca,4,2,4,290,7000.0,7068.0,6800.0
32859,Casa,Campo Grande,1,0,0,50,600.0,NaN,NaN
32865,Casa de Vila,Pavuna,2,0,0,55,600.0,NaN,NaN
32867,Casa de Condomínio,Barra da Tijuca,4,3,2,250,7500.0,1300.0,680.0
32869,Casa de Condomínio,Barra da Tijuca,4,3,4,460,12000.0,1000.0,1200.0
32893,Casa,Recreio dos Bandeirantes,4,2,2,352,6500.0,NaN,NaN
32898,Casa de Condomínio,Barra da Tijuca,5,2,5,554,20000.0,1892.0,1743.0
32908,Casa de Condomínio,Freguesia (Jacarepaguá),3,3,1,155,2000.0,530.0,1250.0
32911,Casa,Bento Ribeiro,2,1,0,60,1400.0,NaN,NaN
32924,Casa de Condomínio,Barra da Tijuca,3,5,3,1000,20000.0,3000.0,NaN
32931,Casa,Centro,5,0,1,160,5000.0,NaN,80.0
32952,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0

## 3. how many real estates with Area between 60 and 100 meters

In [24]:
area_selection = (df_realestate['Area'] >= 60) & (df_realestate['Area'] <= 100)
df_area = df_realestate[area_selection]
print("There are {} real estate between 60 and 100 meters in the database".format(df_area.shape[0]))

There are 10187 houses in the database

## 4. Show real estate with 4 bedrooms and rent less than 2000.00

In [22]:
bed_and_price_selection = (df_realestate['Quartos']==4) & (df_realestate['Valor'] < 2000)
df_bed_and_price = df_realestate[bed_and_price_selection]
df_bed_and_price

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
701,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,830.0,NaN
1465,Apartamento,Taquara,4,1,1,110,1900.0,NaN,NaN
2874,Casa,Campo Grande,4,1,4,100,1600.0,NaN,NaN
3075,Casa,Engenho de Dentro,4,3,0,120,1500.0,NaN,NaN
3218,Apartamento,Recreio dos Bandeirantes,4,2,2,125,1700.0,NaN,90.0
3419,Casa de Vila,Méier,4,0,1,85,1600.0,NaN,NaN
5849,Casa,Campo Grande,4,1,0,140,1700.0,NaN,NaN
5852,Apartamento,Campo Grande,4,2,1,115,1900.0,500.0,NaN
6456,Apartamento,Recreio dos Bandeirantes,4,2,1,105,1900.0,1492.0,205.0
7520,Apartamento,Cidade Nova,4,0,0,110,1300.0,NaN,NaN
9716,Apartamento,Pechincha,4,1,2,178,1900.0,1100.0,270.0
10132,Casa,Riachuelo,4,0,1,100,1800.0,NaN,40.0
10144,Casa,Méier,4,1,1,125,1900.0,NaN,NaN
11323,Apartamento,Recreio dos Bandeirantes,4,2,3,280,1800.0,1400.0,580.0
11367,Apartamento,Recreio dos Bandeirantes,4,3,2,250,1500.0,1380.0,700.0
11675,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,1093.0,183.0
14890,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,1038.0,158.0
16078,Casa de Condomínio,Taquara,4,1,0,110,1750.0,550.0,993.0
17637,Apartamento,Leme,4,0,1,185,1800.0,2000.0,270.0
18453,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,930.0,150.0
19553,Apartamento,Camorim,4,1,1,96,1350.0,747.0,NaN
20077,Apartamento,Barra da Tijuca,4,3,4,148,1600.0,1766.0,NaN
20633,Casa,Praça Seca,4,1,1,128,1600.0,NaN,228.0
21973,Casa de Condomínio,Freguesia (Jacarepaguá),4,2,1,120,1800.0,195.0,30.0
22000,Casa,Pedra de Guaratiba,4,1,0,100,1300.0,NaN,NaN
23284,Apartamento,Campo Grande,4,2,2,160,1900.0,880.0,NaN
23453,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,912.0,160.0
23608,Apartamento,Rio Comprido,4,1,0,110,1650.0,500.0,NaN
24572,Casa,Campo Grande,4,3,0,120,1700.0,NaN,NaN
25993,Apartamento,Taquara,4,3,1,190,1200.0,NaN,NaN
26178,Casa,Campo Grande,4,0,1,366,1890.0,NaN,208.0
26549,Casa,Campo Grande,4,0,0,159,1800.0,NaN,NaN
26750,Casa,Braz de Pina,4,1,0,99,1800.0,NaN,NaN
27033,Casa,Campo Grande,4,1,3,100,1600.0,NaN,NaN
28421,Casa,Campo Grande,4,1,2,180,1850.0,300.0,NaN
29517,Apartamento,Campo Grande,4,1,1,80,1600.0,950.0,NaN
30670,Apartamento,Barra da Tijuca,4,3,4,148,1500.0,1600.0,196.0
31382,Apartamento,Vargem Grande,4,0,1,180,1900.0,NaN,176.0
31840,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,1038.0,NaN
32064,Casa,Campo Grande,4,2,0,120,1600.0,NaN,NaN

In [23]:
# renaming columns to english
df_bed_and_price.columns = ["Type", "Location", "Bedrooms", "Parking spots", "Suite", "Area", "Rent", "Condo fee", "City fee"]
df_bed_and_price

,Type,Location,Bedrooms,Parking spots,Suite,Area,Rent,Condo fee,City fee
701,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,830.0,NaN
1465,Apartamento,Taquara,4,1,1,110,1900.0,NaN,NaN
2874,Casa,Campo Grande,4,1,4,100,1600.0,NaN,NaN
3075,Casa,Engenho de Dentro,4,3,0,120,1500.0,NaN,NaN
3218,Apartamento,Recreio dos Bandeirantes,4,2,2,125,1700.0,NaN,90.0
3419,Casa de Vila,Méier,4,0,1,85,1600.0,NaN,NaN
5849,Casa,Campo Grande,4,1,0,140,1700.0,NaN,NaN
5852,Apartamento,Campo Grande,4,2,1,115,1900.0,500.0,NaN
6456,Apartamento,Recreio dos Bandeirantes,4,2,1,105,1900.0,1492.0,205.0
7520,Apartamento,Cidade Nova,4,0,0,110,1300.0,NaN,NaN
9716,Apartamento,Pechincha,4,1,2,178,1900.0,1100.0,270.0
10132,Casa,Riachuelo,4,0,1,100,1800.0,NaN,40.0
10144,Casa,Méier,4,1,1,125,1900.0,NaN,NaN
11323,Apartamento,Recreio dos Bandeirantes,4,2,3,280,1800.0,1400.0,580.0
11367,Apartamento,Recreio dos Bandeirantes,4,3,2,250,1500.0,1380.0,700.0
11675,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,1093.0,183.0
14890,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,1038.0,158.0
16078,Casa de Condomínio,Taquara,4,1,0,110,1750.0,550.0,993.0
17637,Apartamento,Leme,4,0,1,185,1800.0,2000.0,270.0
18453,Apartamento,Recreio dos Bandeirantes,4,2,1,160,1900.0,930.0,150.0
19553,Apartamento,Camorim,4,1,1,96,1350.0,747.0,NaN
20077,Apartamento,Barra da Tijuca,4,3,4,148,1600.0,1766.0,NaN
20633,Casa,Praça Seca,4,1,1,128,1600.0,NaN,228.0
21973,Casa de Condomínio,Freguesia (Jacarepaguá),4,2,1,120,1800.0,195.0,30.0
22000,Casa,Pedra de Guaratiba,4,1,0,100,1300.0,NaN,NaN
23284,Apartamento,Campo Grande,4,2,2,160,1900.0,880.0,NaN
23453,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,912.0,160.0
23608,Apartamento,Rio Comprido,4,1,0,110,1650.0,500.0,NaN
24572,Casa,Campo Grande,4,3,0,120,1700.0,NaN,NaN
25993,Apartamento,Taquara,4,3,1,190,1200.0,NaN,NaN
26178,Casa,Campo Grande,4,0,1,366,1890.0,NaN,208.0
26549,Casa,Campo Grande,4,0,0,159,1800.0,NaN,NaN
26750,Casa,Braz de Pina,4,1,0,99,1800.0,NaN,NaN
27033,Casa,Campo Grande,4,1,3,100,1600.0,NaN,NaN
28421,Casa,Campo Grande,4,1,2,180,1850.0,300.0,NaN
29517,Apartamento,Campo Grande,4,1,1,80,1600.0,950.0,NaN
30670,Apartamento,Barra da Tijuca,4,3,4,148,1500.0,1600.0,196.0
31382,Apartamento,Vargem Grande,4,0,1,180,1900.0,NaN,176.0
31840,Apartamento,Recreio dos Bandeirantes,4,2,2,160,1900.0,1038.0,NaN
32064,Casa,Campo Grande,4,2,0,120,1600.0,NaN,NaN